Shqipify/Models/CommentViewModel.cs
using Shqipify.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shqipify.Models
{
    public class CommentViewModel
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("PostId")]
        public int PostId { get; set; }
        [Required]
        public string? Text { get; set; }
        public string? Author { get; set; }
    }
}

Shqipify/Models/DBEnteties/Comments.cs
using Shqipify.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Shqipify.Models.DBEnteties
{
    public class Comments
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("PostId")]
        public int PostId { get; set; }
        public string? Text { get; set; }
        public string? Author { get; set; }
    }
}

Shqipify/Controllers/MyPostsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shqipify.Areas.Identity.Data;
using Shqipify.DAL;
using Shqipify.Models.DBEnteties;
using Shqipify.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Shqipify.Controllers
{
    public class MyPostsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        private readonly PostDBContext _context;



        public MyPostsController(PostDBContext context, UserManager<AppUser> userManager)
        {
            this._context = context;
            _userManager = userManager;
        }
        [HttpGet]
        public  IActionResult Index()
        {
            var loggedUser =  _userManager.GetUserId(User);
            var posts = _context.Posts.Where(p=>p.UserId==loggedUser).ToList();
            if (posts != null)
            {
                List<PostViewModel> postList = new List<PostViewModel>();

                foreach (var post in posts)
                {
                    List<Comments> comments = _context.Comments.Where(c => c.PostId == post.Id).ToList();
                    var temoPost = new PostViewModel()
                    {
                        Id = post.Id,
                        Title = post.Title,
                        Description = post.Description,
                        Author = post.Author,
                        Image = post.Image,
                        CreatedTime = post.CreatedTime,
                        Comments = comments,
                        SelectedUni=post.university
                    };
                    postList.Add(temoPost);
                }
                return View(postList);
            }
            else
            {
                return View();
            }


        }

        [HttpGet]

        public async Task<IActionResult> Update(int? id)
        {
            if (id != null)
            {
               
                var post = await _context.Posts.FirstOrDefaultAsync(u => u.Id == id);
                var model = new PostViewModel()
                {
                    Id = post.Id,
                    Title=post.Title,
                    Description=post.Description,
                    Author=post.Author,
                    SelectedUni=post.university,
                    CreatedTime=post.CreatedTime,
                    Image=post.Image,
                    UserId=post.UserId,

                };

                
                return View(model);
            }
            else
            {
                return View("Index");
            }

        }


        [HttpPost]


        public async Task<IActionResult> UpdateAsync(PostViewModel postData)
        {

            if (ModelState.IsValid)
            {
                var post = await _context.Posts.FindAsync(postData.Id);
                if (post != null)
                {
                    post.Id = postData.Id;
                    post.Image = postData.Image;
                    post.Author = postData.Author;
                    post.UserId = postData.UserId;
                    post.university = postData.SelectedUni;
                    post.Title = postData.Title;
                    post.Description = postData.Description;
                    post.CreatedTime = postData.CreatedTime;


                }
               await _context.SaveChangesAsync();
                TempData["successMessage"] = "Post edited successfully";
                return View("Index");

            }
            else
            {
                TempData["errorMessage"] = "Model data not valid!";
                return View();

            }

        }
        [HttpPost, ActionName("DeletePost")]


        public async Task<IActionResult> DeleteAsync(int id)
        {
            var uni = await _context.Posts.FindAsync(id);
            if (uni != null)
            {
                _context.Posts.Remove(uni);

            }
            await _context.SaveChangesAsync();
            TempData["successMessage"] = "Uni deleted successfully";
            return RedirectToAction(nameof(Index));

        }


    }
}

Shqipify/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Shqipify.Areas.Identity.Data;
using Shqipify.DAL;
using Shqipify.Models;
using Shqipify.Models.DBEnteties;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Shqipify.Controllers
{
    public class PostController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
       
        private readonly PostDBContext _context;



        public PostController(PostDBContext context, UserManager<AppUser> userManager)
        {
            this._context = context;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index()
        {
  
            var posts = _context.Posts.ToList();
            if (posts != null)
            {
                List<PostViewModel> postList = new List<PostViewModel>();

                foreach (var post in posts)
                {
                    List<Comments> comments = _context.Comments.Where(c => c.PostId == post.Id).ToList();
                    var temoPost = new PostViewModel()
                    {
                        Id = post.Id,
                        Title = post.Title,
                        Description = post.Description,
                        Author = post.Author,
                        Image = post.Image,
                        CreatedTime = post.CreatedTime,
                        Comments = comments,
                        SelectedUni=post.university
                      
                    };
                    postList.Add(temoPost);
                }
                TempData.Keep();
                return View(postList);
            }
            else
            {
                TempData.Keep();
                return View();
            }


        }
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var universities = _context.Universities.ToList();
            var model = new PostViewModel();
            model.University = new List<SelectListItem>();
            foreach(var u in universities)
            {
                model.University.Add(new SelectListItem { Text = u.Name, Value = u.Name });
            }
            TempData.Keep();
            return View(model);
        }
      
        [Authorize]
        [HttpPost]


        public async Task<IActionResult> CreateAsync(PostViewModel postData)
        {
            var loggedUser = await _userManager.GetUserAsync(User);


            if (ModelState.IsValid && loggedUser!=null)
            {
                var post = new Post()
                {
                    Title = postData.Title,
                    Description = postData.Description,
                    Image = postData.Image,
                    Author= loggedUser.Firstname +" "+ loggedUser.Lastname,
                    UserId= loggedUser.Id,
                    CreatedTime=DateTime.Now,
                    university=postData.SelectedUni
                    

                };
                _context.Posts.Add(post);
                _context.SaveChanges();
                TempData["successMessage"] = "Post added successfully";
                return RedirectToAction("Index");

            }
            else
            {
                TempData["errorMessage"] = "Model data nnot valid!";
                TempData.Keep();
                return View();

            }
         
        }


        public async Task<IActionResult> CommentAsync(CommentViewModel commentData)
        {
            var loggedUser = await _userManager.GetUserAsync(User);


            if (ModelState.IsValid && loggedUser != null)
            {
                var comment = new Comments()
                {
                    Id=commentData.Id,
                    PostId = commentData.PostId,
                    Author = loggedUser.Firstname + " "+ loggedUser.Lastname,
                    Text = commentData.Text

                };
                _context.Comments.Add(comment);
                _context.SaveChanges();
                TempData["successMessage"] = "Comment added successfully";
                TempData.Keep();

                return RedirectToAction("Index");

            }
            else
            {
                TempData["errorMessage"] = "Model data nnot valid!";
                TempData.Keep();

                return View("Index");

            }

        }


    }
}

Shqipify/Views/Shared/_Comment.cshtml
@model CommentViewModel

<form asp-controller="Post" asp-action="Comment" method="post">
    <input type="text" class="form-control" asp-for="PostId" hidden />
    <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
        <div class="d-flex flex-start w-100">
            <div class="form-outline w-100">
                <label class="form-label" for="textAreaExample">Shkruaj nje koment ...</label>
                <textarea asp-for="Text" class="form-control" id="textAreaExample" rows="4"
                          style="background: #fff;"></textarea>
            </div>
        </div>
        <div class="float-end mt-2 pt-1">
            <button  type="submit" class="btn btn-primary btn-sm">Post comment</button>
        </div>
    </div>
    
</form>

Shqipify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shqipify</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shqipify.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="position-sticky">
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shqipify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Create">Create Post</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyPosts" asp-action="Index">My Posts</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin panel</a>
                            </li>
                        }
                       
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>